# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 이승윤 LeeSeungYun
email: ileilliat@gamil.com
description: >- # this means to ignore newlines until next contents
  일상의 고민을 해결하는 개발자, 이승윤 입니다. LeeSeungYun1020
domain: leeseungyun1020.github.io
baseurl: ""
url: ""
#twitter_username: leeseungyun
github_username:  LeeSeungYun1020


# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - configuration.rb


#collections:


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /docs/:title